export const data = {
  Languages: [
    "Java",
    ".NET",
    "PHP",
    "Ruby",
    "Python",
    "JavaScript",
    "HTML5",
    "CSS",
    "C/C++",
    "C#",
    "Go",
    "Rust",
  ],
  "Web-Technologies": [
    "Angular",
    "Vue.js",
    "Node.js",
    "React.js",
    "Ember.js",
    "ASP.NET",
    "Laravel",
    "Django",
    "Express",
    "Rails",
    "Spring/Spring Boot",
    "Groovy/Grails",
    "Revel",
    "Blazor",
  ],
  "Mobile-Technologies": [
    "Kotlin",
    "Flutter",
    "React Native",
    "Xamarin",
  ],
  "Operating-System": ["Android", "iOS/Swift", "Linux", "Windows", "macOS"],
  Databases: [
    "MySQL/MS SQL",
    "Redis",
    "CouchDB",
    "Oracle",
    "MongoDB",
    "Cassandra",
    "PostgreSQL",
    "SQLite",
    "Neo4J",
  ],
  "Web-Servers": [
    "Apache Tomcat",
    "Jetty",
    "GlassFish",
    "JBoss",
    "Nginx",
    "Microsoft IIS",
  ],
  "Cloud & Deployment": [
    "Docker",
    "Kubernetes",
    "Azure",
    "AWS",
    "Heroku",
    "GoogleCloud",
    "Weblogic",
  ],
  "AI/ML": [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "TensorFlow",
    "Keras",
    "Spacy",
    "Pytorch",
  ],
};
