export const data = {
  Languages: [
    "Java",
    "Kotlin",
    "Swift",
    "R",
    "PHP",
    "Ruby",
    "Python",
    "Matlab",
    "JavaScript",
    "TypeScript",
    "Scala",
    "HTML5",
    "CSS",
    "SQL",
    "NoSQL",
    "C/C++",
    "C#",
    "Go",
    "Rust",
    "Perl",
  ],
  "Libraries and Frameworks": [
    "Angular",
    "Vue.js",
    "Node.js",
    "React.js",
    "Ember.js",
    ".NET",
    "Laravel",
    "Django",
    "Flask",
    "Express",
    "Rails",
    "Spring/Spring Boot",
    "Groovy/Grails",
    "Revel",
    "Blazor",
    "Bootstrap",
    "Tailwind CSS",
    "SASS",
    "npm",
    "yarn",
    "JQuery",
  ],
  "Mobile-Technologies": [
    "Android Studio (Android)",
    "Xcode (iOS)",
    "Flutter",
    "React Native",
    "Xamarin",
    "Ionic",
  ],
  "Operating-System": [
    "Android",
    "iOS/Swift",
    "Linux",
    "Windows",
    "macOS",
    "RTOS (Real-Time Operating System)",
  ],
  Databases: [
    "MySQL/MS SQL",
    "Redis",
    "CouchDB",
    "Oracle",
    "MongoDB",
    "Cassandra",
    "PostgreSQL",
    "DB2",
    "SQLite",
    "Neo4J",
  ],
  "Web-Servers": [
    "Apache Tomcat",
    "Jetty",
    "GlassFish",
    "JBoss",
    "Nginx",
    "Microsoft IIS",
    "OpenResty",
    "LiteSpeed Web Server",
    "Phusion Passenger",
    "Google Cloud Functions",
    "SAP NetWeaver",
  ],
  "Cloud & Deployment": [
    "Ansible",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Git",
    "GitLab",
    "Azure",
    "AWS",
    "Heroku",
    "GoogleCloud",
    "IBM Cloud",
  ],
  "Data Science": [
    "Data Manipulation",
    "Data Visualization",
    "Data Analysis",
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
  ],
  "AI/ML": [
    "Pandas",
    "Natural Language Processing (NLP)",
    "Scikit Learn",
    "theano",
    "Computer Vision",
    "TensorFlow",
    "Keras",
    "Caffe",
    "Google ML Kit",
    "Spacy",
    "Pytorch",
  ],
  "SDLC models": [
    "Agile",
    "Scrum",
    "DevOps",
    "Lean",
    "Iterative",
    "Spiral",
    "Waterfall",
    "Prototype",
    "Big Bang",
    "V-Shaped",
    "Incremental",
  ],
  "Testing-Tools": [
    "Spira Test",
    "Selenium",
    "Rapise",
    "Lambda Test",
    "Cypress",
    "Eggplant",
  ],
  "Development-Platforms": [
    "IntelliJ IDEA",
    "RStudio",
    "JupyterLab",
    "Visual Studio Code",
    "PyCharm",
    "Atom",
    "NetBeans",
    "Code::Blocks",
    "Eclipse"
  ],
  "API protocols": ["SOAP", "REST", "JSON-RPC", "gRPC", "GraphQL", "Thrift"],
};
