export const resourceLinks = {
  Java: "https://dev.java/",
  Kotlin: "https://kotlinlang.org/",
  Swift: "https://www.swift.org/",
  R: "https://www.w3schools.com/r/",
  PHP: "https://php.org/",
  Ruby: "https://www.ruby-lang.org/en/",
  Python: "https://www.python.org/",
  Matlab: "https://in.mathworks.com/products/matlab/getting-started.html",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  TypeScript: "https://www.typescriptlang.org/",
  Scala: "https://www.scala-lang.org/",
  HTML5: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  CSS: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  SQL: "https://www.w3schools.com/sql/",
  NoSQL: "https://www.javatpoint.com/nosql-databases",
  "C/C++": "https://www.w3schools.com/cpp/",
  "C#": "https://dotnet.microsoft.com/en-us/learn/csharp",
  Go: "https://go.dev/",
  Rust: "https://www.rust-lang.org/",
  Perl: "https://learn.perl.org/",
  Angular: "https://angular.dev/",
  "Vue.js": "https://vuejs.org/",
  "Node.js": "https://nodejs.org/en",
  "React.js": "https://react.dev/",
  "Ember.js": "https://emberjs.com/",
  ".NET": "https://dotnet.microsoft.com/en-us/",
  Laravel: "https://laravel.com/",
  Django: "https://www.djangoproject.com/",
  Flask: "https://flask.palletsprojects.com/en/3.0.x/",
  Express: "https://expressjs.com/",
  Rails: "https://guides.rubyonrails.org/index.html",
  "Spring/Spring Boot": "https://spring.io/",
  "Groovy/Grails": "https://groovy-lang.org/index.html",
  Revel: "",
  Blazor: "https://www.learnblazor.com/",
  Bootstrap: "https://getbootstrap.com/",
  "Tailwind CSS": "https://tailwindcss.com/",
  SASS: "https://sass-lang.com/",
  npm: "https://docs.npmjs.com/",
  yarn: "https://yarnpkg.com/",
  JQuery: "https://learn.jquery.com/",
  "Android Studio (Android)": "https://developer.android.com/",
  "Xcode (iOS)": "https://developer.apple.com/xcode/",
  Flutter: "https://flutter.dev/",
  "React Native": "https://reactnative.dev/",
  Xamarin: "https://www.tutorialspoint.com/xamarin/index.htm",
  Ionic: "https://ionicframework.com/docs/",
  Android: "https://www.javatpoint.com/android-operating-system",
  "iOS/Swift": "https://www.tutorialspoint.com/ios/index.htm",
  Linux: "https://linuxjourney.com/",
  Windows: "https://edu.gcfglobal.org/en/",
  macOS: "https://support.apple.com/en-in/guide/mac-help/welcome/mac",
  "RTOS (Real-Time Operating System)": "https://www.freertos.org/index.html",
  "MySQL/MS SQL": "https://dev.mysql.com/doc/mysql-tutorial-excerpt/8.0/en/",
  Redis: "https://redis.io/",
  CouchDB: "https://couchdb.apache.org/",
  Oracle:
    "https://learn.oracle.com/ols/learning-path/become-a-oracle-sql-expert/55700/55730",
  MongoDB: "https://www.mongodb.com/",
  Cassandra: "https://cassandra.apache.org/_/index.html",
  PostgreSQL: "https://www.postgresql.org/",
  DB2: "https://www.db2tutorial.com/",
  SQLite: "https://www.sqlitetutorial.net/",
  Neo4J: "https://neo4j.com/",
  "Apache Tomcat":
    "https://tomcat.apache.org/tomcat-3.2-doc/uguide/tomcat_ug.html",
  Jetty: "https://www.baeldung.com/jetty-embedded",
  GlassFish: "https://docs.oracle.com/cd/E19798-01/821-1757/aboaa/index.html",
  JBoss:
    "https://developers.redhat.com/products/eap/overview#:~:text=JBoss%20EAP%20includes%20everything%20needed,popular%20open%20source%20project%20WildFly.",
  Nginx: "https://nginx.org/",
  "Microsoft IIS":
    "https://learn.microsoft.com/en-us/iis/get-started/getting-started-with-iis/getting-started-with-the-iis-manager-in-iis-7-and-iis-8",
  OpenResty: "",
  "LiteSpeed Web Server": "https://docs.litespeedtech.com/lsws/",
  "Phusion Passenger": "https://www.phusionpassenger.com/library/",
  "Google Cloud Functions": "https://cloud.google.com/functions",
  "SAP NetWeaver": "https://www.tutorialspoint.com/sap_netweaver/index.htm",
  Ansible: "https://docs.ansible.com/",
  Docker: "https://www.docker.com/",
  Kubernetes: "https://kubernetes.io/",
  Jenkins: "https://www.jenkins.io/",
  Git: "https://git-scm.com/",
  GitLab: "https://docs.gitlab.com/",
  Azure: "https://learn.microsoft.com/en-us/training/azure/",
  AWS: "https://aws.amazon.com/?nc2=h_lg",
  Heroku: "https://www.heroku.com/home",
  GoogleCloud:
    "https://cloud.google.com/?_gl=1*g1erz3*_up*MQ..&gclid=EAIaIQobChMI24HGhvvJhwMV79AWBR3-XCFWEAAYASAAEgJ8efD_BwE&gclsrc=aw.ds",
  "IBM Cloud": "https://www.ibm.com/training/cloud",
  "Data Manipulation": "https://www.geeksforgeeks.org/data-manipulation/",
  "Data Visualization": "https://www.kaggle.com/learn/data-visualization",
  "Data Analysis":
    "https://learn.microsoft.com/en-us/training/paths/data-analytics-microsoft/",
  "Artificial Intelligence":
    "https://www.nvidia.com/en-us/learn/ai-learning-essentials/?ncid=pa-so-godi-211743-vt16-AI-Learning-Generic-e&_bt=704767943402&_bk=getting%20started%20in%20ai&_bm=e&_bn=g&_bg=161461054742&gad_source=1&gclid=EAIaIQobChMIrJuE7fvJhwMVi-AWBR2pwRzeEAAYASAAEgIkEPD_BwE",
  "Machine Learning": "https://machinelearningmastery.com/start-here/",
  "Deep Learning": "https://www.kaggle.com/learn/intro-to-deep-learning",
  Pandas: "https://pandas.pydata.org/docs/index.html",
  "Natural Language Processing (NLP)":
    "https://www.deeplearning.ai/resources/natural-language-processing/",
  "Scikit Learn": "https://scikit-learn.org/stable/#",
  theano: "https://www.tutorialspoint.com/theano/index.htm",
  "Computer Vision": "https://www.kaggle.com/learn/computer-vision",
  TensorFlow: "https://www.tensorflow.org/",
  Keras: "https://keras.io/",
  Caffe: "https://caffe.berkeleyvision.org/",
  "Google ML Kit": "https://developers.google.com/ml-kit",
  Spacy: "https://spacy.io/",
  Pytorch: "https://pytorch.org/",
  Agile: "https://www.tutorialspoint.com/agile/index.htm",
  Scrum: "https://www.scrum.org/",
  DevOps:
    "https://learn.microsoft.com/en-us/training/career-paths/devops-engineer",
  Lean: "",
  Iterative: "https://www.javatpoint.com/software-engineering-iterative-model",
  Spiral: "https://www.geeksforgeeks.org/software-engineering-spiral-model/",
  Waterfall: "https://www.geeksforgeeks.org/waterfall-model/",
  Prototype:
    "https://www.geeksforgeeks.org/software-engineering-prototyping-model/",
  "Big Bang": "https://www.tutorialspoint.com/sdlc/sdlc_bigbang_model.htm",
  "V-Shaped": "https://www.tutorialspoint.com/sdlc/sdlc_v_model.htm",
  Incremental:
    "https://www.javatpoint.com/software-engineering-incremental-model",
  "Spira Test": "https://www.inflectra.com/Products/SpiraTest/",
  Selenium: "https://www.javatpoint.com/selenium-tutorial",
  Rapise: "https://www.inflectra.com/Products/Rapise/Documentation.aspx",
  "Lambda Test": "https://www.lambdatest.com/learning-hub/",
  Cypress: "https://learn.cypress.io/",
  Eggplant: "https://support.eggplantsoftware.com/training-and-certifications",
  "IntelliJ IDEA": "https://www.jetbrains.com/idea/download/?section=windows",
  RStudio: "https://posit.co/products/open-source/rstudio/",
  JupyterLab: "https://jupyter.org/",
  "Visual Studio Code": "https://code.visualstudio.com/",
  PyCharm: "https://www.jetbrains.com/pycharm/",
  Atom: "https://atom-editor.cc/",
  NetBeans: "https://netbeans.apache.org/front/main/index.html",
  "Code::Blocks": "https://www.codeblocks.org/",
  Eclipse: "https://eclipseide.org/",
  SOAP: "https://www.tutorialspoint.com/soap/index.htm",
  REST: "https://www.restapitutorial.com/",
  "JSON-RPC": "https://www.geeksforgeeks.org/what-is-json-rpc-in-ethereum/",
  gRPC: "https://grpc.io/",
  GraphQL: "https://graphql.org/",
  Thrift: "https://thrift.apache.org/",
};
